### ISSUE TITLE
Error: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by pf55351** [poowf/react-native-argon2#15]
Hi, I have the follow error when i call aragon2 function in RN. The problem is only with Android

Error: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference

RN: 0.64.2
RN argon2: 2.0.1

How could i fix this issue?
Thank you

**Comment by zanechua** [comment]
Hey @pf55351.

Please provide a sample repository for reproduction

**Comment by pf55351** [comment]
Hi @zanechua,
thank you for your answer... 

I looked more closely at the code and made a mistake myself.
So the module works perfectly.

Thank you
