### ISSUE TITLE
Exception - null is not an object (evaluating 'RNArgon2Module.argon2')

### ISSUE THREAD

**Issue by cuBREbRA** [poowf/react-native-argon2#6]
Hello,
Whenever I try to run your library I get error - Exception - null is not an object (evaluating 'RNArgon2Module.argon2')

**Comment by zanechua** [comment]
Please provide environment information and which version of the package you're running

**Comment by spieglt** [comment]
I'm also seeing this, using Mint 19, iOS, Expo, and `"react-native-argon2": "^2.0.0"`.

**Comment by zanechua** [comment]
Could I get the same ask as above and get your environment information?

```
react-native info
```

**Comment by spieglt** [comment]
Ah, since I'm using Expo, I don't have the react-native CLI installed. I guess this repo probably only works if you're using that?

**Comment by zanechua** [comment]
I'll try and see in my free time if I can get support for Expo but could you provide me a starting point with your Expo project?

You can get environmental info for expo with the following command.

```
expo diagnostics
```

**Comment by spieglt** [comment]
Thanks!
```
Expo CLI 4.0.13 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.2/bin/npm
    npmPackages:
      expo: ^39.0.5 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed
```

**Comment by zanechua** [comment]
Has this issue been resolved? @cuBREbRA

**Comment by danielcdcj** [comment]
Hi,
does anyone know how to get this library working in an Expo project?
Thanks in advance!

**Comment by lbxa** [comment]
> Hi, does anyone know how to get this library working in an Expo project? Thanks in advance!

@danielcdcj, nope.
